### ISSUE TITLE
cmdbuild - container is not starting

### ISSUE THREAD

**Issue by topspit** [Quentinvarquet/docker-cmdbuild#1]
$ docker run -itd -p 8080:8080 quentinv/cmdbuild:latest
adbd1d434ebe660a49088016f39447396f48d33b0dcdd50d068aedd4dce9df67

$ docker logs adb
standard_init_linux.go:187: exec user process caused "no such file or directory"

I guess i need a db backend... Do you have an example docker-compose.yml with postgres?

**Comment by Quentinvarquet** [comment]
Hello,

Yes ! 

https://github.com/Quentinvarquet/docker-cmdbuild/blob/master/tomcat7/t7-2.4.3/Docker-Compose/Network/docker-compose.yml

For the configuration you can read the last part in the readme : 


https://github.com/Quentinvarquet/docker-cmdbuild/blob/master/README.md

**Comment by topspit** [comment]
Hello Quentin,

thank you for you fast response.

But also with the docker-compose file its not working... same error:

Here is my docker-compose.yml:


[docker-compose.txt](https://github.com/Quentinvarquet/docker-cmdbuild/files/1284562/docker-compose.txt)


i run this command:

docker-compose up -d

but the cmdbuild_tomcat_1 is not starting:

$ docker logs cmdbuild_tomcat_1
standard_init_linux.go:187: exec user process caused "no such file or directory"
standard_init_linux.go:187: exec user process caused "no such file or directory"
standard_init_linux.go:187: exec user process caused "no such file or directory"

do you have any idea what is in my compose file missing?

**Comment by Quentinvarquet** [comment]
Hm..

Wich distribution are you using ?

**Comment by topspit** [comment]
cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)

docker version
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:53:49 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 23:01:50 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by topspit** [comment]
Ok i just run the same config on this distr:
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

It's working here :)

Thank you for the hint.

**Comment by luca-ma** [comment]
Hi,
containers start correctly, but cmdbuild can't connect to postgres.
I can't also connect outside postgresql container to postgres via psql.
thanks
