### ISSUE TITLE
shark server

### ISSUE THREAD

**Issue by rabidmullet** [Quentinvarquet/docker-cmdbuild#3]
The container starts fine but it looks like shark isn't installed. When logging in I get the error "class requestforchange not found". I've tried to copy the war file to webapps and run it but can't get it working. Can you help?

**Comment by Quentinvarquet** [comment]
Hello @themoss , sorry i was not available.

I confirm, Shark isn't installed :) I prepared (long time ago) a full dockerfile for cmdbuild with Shark. If you want I can try to find it :)

**Comment by rabidmullet** [comment]
Yeah if you have a docketfile with Shark that would be awesome... if it’s not too much trouble?

**Comment by Quentinvarquet** [comment]
Hello, I found the first dockerfile i made.

It's not completely working anymore i have to update it. I will try to work on it this week and add it to this repo.
